import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Caveat } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import Navbar from "@/components/navbar";
import { PaintStrokes } from "@/components/paint-strokes";
import Footer from "@/components/footer";
import { cn } from "@/lib/utils";

const headingFont = Caveat({subsets: ["latin"], variable: "--font-caveat"});
const inter = Inter({subsets: ['latin'], variable: '--font-inter'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, inter.variable, headingFont.variable)}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col lg:gap-5 lg:px-90 lg:py-7 relative">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem  
          disableTransitionOnChange
        >
          <PaintStrokes />
          <Navbar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
