import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, JetBrains_Mono, Caveat } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import Navbar from "@/components/navbar";
import { PaintStrokes } from "@/components/paint-strokes";
import Footer from "@/components/footer";
import { cn } from "@/lib/utils";

const headingFont = Caveat({subsets: ["latin"], variable: "--font-caveat"});
const inter = Inter({subsets: ["latin"], variable: "--font-inter"});
const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Parth Naik",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, inter.variable, jetBrainsMono.variable, headingFont.variable)}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col gap-3 px-4 py-3 relative sm:px-6 lg:gap-5 lg:px-12 lg:py-7 xl:px-90">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem  
          disableTransitionOnChange
        >
          <PaintStrokes />
          <main className="flex flex-1 flex-col gap-2 px-2 sm:px-3 lg:gap-5 lg:px-5">
            <Navbar />
            {children}
            <Footer />
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
